Implement liveReload utils to simplify live reload implementations
kontent-ai/smart-link pull request #168
Opened 2024-06-06 17:56 UTC by JiriLojda

### Motivation

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2024-06-11 13:17 UTC, IvanKiral requested changes

2024-06-11 14:00 UTC, JiriLojda commented on src/utils/liveReload.ts
> +  const resolveCodename = resolveElementCodename ?? ((c: string) => camelCasePropertyNameResolver('', c));
The SDK uses camelCase by default. When you don't configure it explicitly you will have camelCase codenames in `item.elements` keys in `res.data` of SDK responses.

2024-06-11 14:12 UTC, JiriLojda commented on src/utils/liveReload.ts
> +        typedElement1.value.length === typedElement2.value.length &&
I am not sure what you mean.

2024-06-12 06:33 UTC, IvanKiral commented on src/utils/liveReload.ts
> +        typedElement1.value.length === typedElement2.value.length &&
oh sorry, I thought that multipleChoice has `mode` property. I have mistaken it for management api

2024-06-14 17:23 UTC, JiriLojda commented on src/utils/liveReload.ts
> +            typedItemElement.linkedItems.map((i) => applyUpdateOnItemOptionallyAsync(i, update, resolveElementCodename))
This is a very good point. I updated the code to handle item cycles properly coupled with a few tests.

2024-06-17 12:53 UTC, IvanKiral submitted a review, later dismissed

2024-06-17 12:53 UTC, IvanKiral commented on README.md
> +  Promise.all(items.map(item => applyUpdateOnItemAndLoadLinkedItems(item, data, fetchItemsFromDeliveryApi)))
don't we want to add below? 
I know its up to anybody how he want to get the items, but this example would save me 2 or 3 minutes till i figured out how to do it :D
```ts
const fetchItemsFromDeliveryApi = (items) => client.items().inFilter(system.codename, items).toAllPromise().then(res => res.data.items)

```

2024-06-19 11:36 UTC, merged